sudo: false
language: python
python:
  - '3.7'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=">=3.2"
install:
  - pip install -q coveralls coverage flake8 Django$DJANGO
  - pip install -r requirements/docs.txt
before_script:
  - psql -c 'CREATE DATABASE newrelic_plugin_agent;' -U postgres
script:
  - flake8 .
  - coverage run setup.py test
  - coverage report --fail-under=98
  - python setup.py install
  - python setup.py build_sphinx
after_success:
  coveralls
